apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: app
spec:
  selector:
    matchLabels:
      app: python
  replicas: 3
  template:
    metadata:
      labels:
        app: python
    spec: 
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - pyapp
      containers:
      - name: pyapp
        image: kpreeti0131/pyapp:latest
        ports:
        - containerPort: 5000
        securityContext:
          allowPrivilegeEscalation: false
      serviceAccountName: test-app
      